# Imports format
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Code format
newline_style = "Unix"
comment_width = 108
max_width = 100
format_strings = true
overflow_delimited_expr = true
reorder_impl_items = true
struct_lit_single_line = false
use_field_init_shorthand = true

# Use "Unnumbered" to skip reporting those tagged with issue number
report_fixme = "Always"
report_todo = "Always"